Login component
ariflogs/RetroUI pull request #3
Opened 2024-09-14 07:56 UTC by rituisboy

added a login component
![image](https://github.com/user-attachments/assets/3d38a29b-0052-42f7-8ee0-4401378d0e79)

2024-09-14 14:20 UTC, ariflogs commented
Thanks for PR @rituisboy.
I left a few comments, please check them out.

2024-09-15 08:05 UTC, ariflogs requested changes

2024-09-15 08:05 UTC, ariflogs commented on components/Login/Login.tsx
> +      <div className="font-head text-3xl text-center px-4 py-2 my-2 ">
please use the typography components.

2024-09-15 08:05 UTC, ariflogs commented on components/Login/Login.tsx
> +          <input
use the `Input` component.

2024-09-15 08:05 UTC, ariflogs commented on components/Login/Login.tsx
> +          <button
use `Button` component.

2024-09-15 08:05 UTC, ariflogs commented on components/Login/Login.tsx
> +    <div className="max-w-80 bg-rose-400  border-2 border-black shadow-md ">
can you remove the rose bg? trying to stay in white, black and the primary color combination for now.

2024-09-15 19:16 UTC, rituisboy commented
i will close this and create new pull request

2024-09-15 19:16 UTC, closed without merging